### ISSUE TITLE
RubyHW1 feedback

### ISSUE THREAD

**Issue by LVALL** [fillson22/RubyHW#1]
Overall looks good, you've used correct methods and optimal solutions, great work!

I've noticed the issue with spacings in some files. That is important thing, so please pay attention to it.

Example from your code:
`p  array.map{|i| i.odd? && (i!=array[0] && i!=array[-1])? i+array[0]:i}`
we need to use whitespaces correctly
`p  array.map { |i| i.odd? && (i != array[0] && i != array[-1]) ? i+array[0] : i }`

The Ruby style guide is a place where you can find all the correct ways for formatting your code: https://github.com/rubocop/ruby-style-guide

**Comment by fillson22** [comment]
Ok. I will learn it.
