### ISSUE TITLE
Фідбек ДЗ 7

### ISSUE THREAD

**Issue by Kashoid23** [fillson22/RubyHW#10]
- [x] В кожному наступному ДЗ починаючи з цього, додавайте гем рубокоп (https://github.com/rubocop/rubocop). І перевіряйте свій код в процесі та перед відправкою (команда в консолі - `rubocop`, або `rubocop -a` якщо хочете, щоб рубокоп сам застосував автоформатування коду). Так ви наочно побачите скільки у вас є з форматуванням виправлень.
- [x] Ви додали гем Faker, думаю варто використовувати його https://github.com/fillson22/RubyHW/blob/main/HW7/blog_v1/db/seeds.rb#L14-L16
- [x] Оновіть валідацію в одну стрічку https://github.com/fillson22/RubyHW/blob/main/HW7/blog_v1/app/models/author.rb#L5-L6
- [x] Почитайте про `dependent: :destroy` та додайте де це потрібно https://guides.rubyonrails.org/association_basics.html#options-for-belongs-to-dependent
- [x] Тут напевно `Tag created` мало бути? https://github.com/fillson22/RubyHW/blob/main/HW7/blog_v1/app/controllers/api/v1/tags_controller.rb#L7
- [x] Зазвичай, коли ми повертаємо статуси, ми використовуємо символьне представлення статусів (навіть якщо це було згенеровано через скаффолд) http://www.railsstatuscodes.com/ . Наприклад `status: :ok`. Перегляньте контроллери та оновіть.
- [x] На занятті обговорювали `@comment.statuses.keys.include?(params[:status])`, що enum не дасть оновити статус на непрописаний. Видаліть та погляньте, що повертається https://github.com/fillson22/RubyHW/blob/main/HW7/blog_v1/app/controllers/api/v1/comments_controller.rb#L17
- [x] Варто обробити помилки в екшині destroy
https://github.com/fillson22/RubyHW/blob/main/HW7/blog_v1/app/controllers/api/v1/likes_controller.rb#L13-L16
- [x] Перейменуйте скоуп `recently_create` на `recent` або `recently_created`, важливо щоб ім'я передавало коректно сенс та результат

**Comment by fillson22** [comment]
Thanks. Fixed.

**Comment by Kashoid23** [comment]
Good job! 👍 I left two comments, you have to receive notifications
