### ISSUE TITLE
Фідбек ДЗ 8

### ISSUE THREAD

**Issue by Kashoid23** [fillson22/RubyHW#11]
- [x] Немає потреби робити запит по ід https://github.com/fillson22/RubyHW/blob/main/HW8/blog_v1/app/serializers/api/v1/article_serializer.rb#L8-L9. Це асоціація, тому можна просто звернутись `object.author.name`. Те саме тут https://github.com/fillson22/RubyHW/blob/main/HW8/blog_v1/app/serializers/api/v1/comment_serializer.rb#L7-L8

А ще краще - створіть ще один серіалайзер Автор, який буде повертати лише імя, тоді не треба будуть ваші кастомні методи. Переконайтесь, що коментарі та артікл підхватили ваш новий серіалайзер

- [x] Пагінацію логічніше застосувати після фільтрації та пошуку, для записів що задовільнили умову
https://github.com/fillson22/RubyHW/blob/main/HW8/blog_v1/app/controllers/api/v1/articles_controller.rb#L5, для змінної екземпляра `@articles`

- [x] Перейменуйте `@article` на `@articles` оскільки це кодеція записів. https://github.com/fillson22/RubyHW/blob/main/HW8/blog_v1/app/controllers/api/v1/articles_controller.rb#L5-L26

- [x] `where` варто винести в скоуп https://github.com/fillson22/RubyHW/blob/main/HW8/blog_v1/app/controllers/api/v1/articles_controller.rb#L15

- [x] order треба застосувати до `@articles`, оскільки ви хочете отримати відсортований та відфільтрований результат https://github.com/fillson22/RubyHW/blob/main/HW8/blog_v1/app/controllers/api/v1/articles_controller.rb#L18

- [x] Не варто робити запит на автора, ви й так в фільтрі будете шукати авторів по імені https://github.com/fillson22/RubyHW/blob/main/HW8/blog_v1/app/controllers/api/v1/articles_controller.rb#L11-L12
Просто перевіряйте чи є параметр params[:author], і тільки тоді фільтруйте

- [x] Це має бути в вигляді скоупа https://github.com/fillson22/RubyHW/blob/main/HW8/blog_v1/app/models/article.rb#L15-L17
https://apidock.com/rails/ActiveRecord/NamedScope/ClassMethods/scope

- [x] Якщо ви шукаєте по імені, то тут буде помилка, оскільки ви перевіряєте id https://github.com/fillson22/RubyHW/blob/main/HW8/blog_v1/app/models/article.rb#L13

**Comment by fillson22** [comment]
Thank you. Fixed.
